### ISSUE TITLE
7z unpack

### ISSUE THREAD

**Issue by heramerom** [ponty/pyunpack#6]
```
from pyunpack import Archive
Archive(thing).extractall(str(thing[0:thing.rfind('/')]))
```

except

```
Traceback (most recent call last):
  File "importItAll.py", line 33, in <module>
    Archive(thing).extractall(str(thing[0:thing.rfind('/')]))
  File "/usr/local/lib/python2.7/dist-packages/pyunpack/__init__.py", line 74, in extractall
    self.extractall_patool(directory, patool_path)
  File "/usr/local/lib/python2.7/dist-packages/pyunpack/__init__.py", line 41, in extractall_patool
    '--outdir=' + directory,
  File "/usr/local/lib/python2.7/dist-packages/easyprocess/__init__.py", line 108, in __init__
self.cmd_as_string = ' '.join(self.cmd)  # TODO: not perfect
TypeError: sequence item 1: expected string, NoneType found
```

[stackoverflow](http://stackoverflow.com/questions/35997103/python-7z-pyunpack-typeerror)

**Comment by ponty** [comment]
Did you install patool?
Can you run patool like this?
```
$ patool
usage: patool [-h] [--verbose] [--non-interactive]
              {extract,list,create,test,repack,recompress,diff,search,formats}
              ...
patool: error: too few arguments
```

**Comment by heramerom** [comment]
Can not install patool
```
Traceback (most recent call last):
  File "/home/geeko/.pyenv/versions/3.5.2/bin/patool", line 24, in <module>
    import patoolib
ImportError: No module named patoolib
```

```
➜   pip install patoolib
Collecting patoolib
  Could not find a version that satisfies the requirement patoolib (from versions: )
No matching distribution found for patoolib

```

**Comment by ponty** [comment]
check the patool homepage for install instructions:
https://wummel.github.io/patool/

First check the package manager for **patool**.
If it is missing then use pip:
```
sudo pip install patool
```

**Comment by heramerom** [comment]
It seems that [patool bug](https://github.com/Homebrew/legacy-homebrew/issues/48754)
